Домашнее Задание 1
banbezv/2018-FS-11-Frontend-Bezverkhniy pull request #1
Opened 2018-10-08 19:49 UTC by banbezv

Вместо alert() функция say(text) выводит блок с текстом, причём с фоном отличным от фона страницы.

Безверхний Андрей FS-11

2018-10-09 10:47 UTC, martinkomitsky requested changes
Исправить замечания

2018-10-09 10:47 UTC, martinkomitsky commented on src/lib/test.js
> +	div.style.background='#00ffdd';
Хорошей практикой является не назначать стили напрямую через js, назначать какой-то css класс, где уже указаны все эти стили. Надо вынести стили в css, а тут добавить class.

2018-10-09 10:47 UTC, martinkomitsky commented on src/index.js
> +say("Text to say");
Проверить во всех js файлах, что там нет смешанных двойных и одинарных кавычек. Нужно оставить только одинарные

2018-10-09 10:47 UTC, martinkomitsky commented on .gitignore
> +
Сюда нужно добавить папку /dist, а саму папку из репозитория удалить, так как она все равно каждый раз пересоздается

2018-10-12 23:33 UTC, banbezv commented
исправил .gitignore, css вынес в отдельный файл

2018-10-13 09:01 UTC, martinkomitsky requested changes
Sorry, на этот раз, последняя правка:
1. Прочитать еще раз условия ДЗ и выполнить последний пункт про eslint и eslint config airbnb
2. Написать npm скрипт для eslint
3. Запустить этот скрипт и исправить все указанные ошибки

2018-10-15 08:45 UTC, martinkomitsky approved these changes

2018-10-15 08:45 UTC, merged

2018-10-15 08:45 UTC, martinkomitsky commented
ок, 10